name: Ping Endpoint Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (UTC)
  workflow_dispatch:        # Allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call your endpoint
        run: |
          curl -s https://lazyping.vercel.app/api/ping
