name: Ping Endpoint Every 15 Minutes

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: # Allows manual trigger too

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call your endpoint
        run: |
          curl -s https://lazyping.vercel.app/api/ping
